### ISSUE TITLE
Cannot create conversation, asking for credentials.

### ISSUE THREAD

**Issue by kyooryoo** [Nexmo/stitch-js-quickstart#25]
I properly configured nexmo-cli, otherwise I cannot create the application "My Conversation App".
But when I goto the next step for creating a conversation with following code:
nexmo conversation:create display_name="Nexmo Chat"
The error comes out as:
Could not read credentials. Please run 'nexmo setup' to setup the CLI. (ENOENT: no such file or directory, open '/Users/lingjiang/.nexmo-app')

I have tried to install nexmo-cli@beta, and uninstall nexmo-cli then install nexmo-cli@beta. Configured nexmo credentials for both situations, but meet the same error still.

Please help. Thank you.

**Comment by AlexLakatos** [comment]
Hi,
You'll need the beta version of the cli. And to create an app first, or do `nexmo app:setup` with the app id and private key.
The create conversation command looks for a local .nexmo-app file to get the app id and private key in order to create the conversation.
