### ISSUE TITLE
5-enable-video quickstarts not showing other member's stream

### ISSUE THREAD

**Issue by abelzx** [Nexmo/stitch-js-quickstart#30]
https://github.com/Nexmo/stitch-js-quickstart/blob/master/examples/5-enable-video/index.html#L199
'localStream' should be 'stream'

https://github.com/Nexmo/stitch-js-quickstart/blob/master/examples/5-enable-video/index.html#L202
'localStream' should be 'stream'

**Comment by AlexLakatos** [comment]
fixed with #32
