### ISSUE TITLE
7-enable-screen-share quickstarts not showing other member's stream and screenshare not working

### ISSUE THREAD

**Issue by abelzx** [Nexmo/stitch-js-quickstart#31]
https://github.com/Nexmo/stitch-js-quickstart/blob/master/examples/7-enable-screen-share/index.html#L201
'localStream' should be 'stream'

https://github.com/Nexmo/stitch-js-quickstart/blob/master/examples/7-enable-screen-share/index.html#L204
'localStream' should be 'stream'

https://github.com/Nexmo/stitch-js-quickstart/blob/master/examples/7-enable-screen-share/index.html#L325
'update' should be 'enable'

**Comment by AlexLakatos** [comment]
fixed with #32
